version: "2.1"
 
services:

  dovecot:
    image: dovecot:$VERSION_DOVECOT
    #build: "https://git.scimetis.net/yohan/docker-dovecot.git"
    container_name: dovecot
    restart: always
    ports:
      - 993:993/tcp
      - 4190:4190/tcp
    networks:
      - mailnet
    volumes:
      - /mnt/volumes/mail_data/data:/home/yohan
      - ./dovecot_expire.sh:/root/dovecot_expire.sh
      - ./users:/etc/dovecot/users
      - ./15-lda.conf:/etc/dovecot/conf.d/15-lda.conf
 
  fetchmail-orange:
    image: fetchmail:$VERSION_FETCHMAIL
    #build: "https://git.scimetis.net/yohan/docker-fetchmail.git"
    container_name: fetchmail-orange
    restart: always
    networks:
      - mailnet
    volumes:
      - ./fetchmailrc-orange:/etc/fetchmailrc

  fetchmail-scimetis:
    image: fetchmail:$VERSION_FETCHMAIL
    #build: "https://git.scimetis.net/yohan/docker-fetchmail.git"
    container_name: fetchmail-scimetis
    restart: always
    networks:
      - mailnet
    volumes:
      - ./fetchmailrc-scimetis:/etc/fetchmailrc
 
  feed2imap:
    image: feed2imap:$VERSION_FEED2IMAP
    #build: "https://git.scimetis.net/yohan/docker-feed2imap.git"
    container_name: feed2imap
    restart: always
    networks:
      - mailnet
    volumes:
      - ./feed2imaprc:/root/feed2imaprc

networks:

  mailnet:
    external: true
